org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2,TLSv1.3 -Djava.net.preferIPv4Stack=true
org.gradle.http.http2.enabled=false
org.gradle.internal.http.socketTimeout=120000
org.gradle.internal.http.connectionTimeout=120000
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
